CREATE DATABASE IF NOT EXISTS MAXproduct_service;
CREATE DATABASE IF NOT EXISTS MAXclient_service;
CREATE DATABASE IF NOT EXISTS MAXorder_service;
CREATE DATABASE IF NOT EXISTS MAXsales_service;
CREATE DATABASE IF NOT EXISTS MAXprovider_service;
