version: '3.8'

services:
  db-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - smartmarket-net

  eureka-server:
    build: ./SmartMarket
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx256m
    networks:
      - smartmarket-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_OPTS=-Xmx256m
    networks:
      - smartmarket-net

  product-service:
    build: ./product-service
    depends_on:
      - eureka-server
      - db-mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/MAXproduct_service?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - JAVA_OPTS=-Xmx256m
    networks:
      - smartmarket-net

  # Aplicar similar para los otros servicios...

networks:
  smartmarket-net:
    driver: bridge
