spring.application.name=client-service
server.port=8085

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/MAXclient_service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
